config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  
  get 'contact' => 'contacts#new'

  get 'contacts/create'

 get 'about' => 'about#index'
  namespace :admin do
  get 'sessions/new'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/show'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/show'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  get 'posts/index'

  get 'posts/show'
  resources :posts, :categories, :comments
  resources  "contacts", only: [:new, :create]
  
  namespace :admin do
  
    resources :posts, :categories, :comments, :users
  end

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  
  validates :name, presence: true
  def self.search(query)
    where("name like ?", "%#{query}%") 
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user  
  has_many :comments
  
  validates :title, presence: true
  validates :category_id, presence: true
  
  validates :body, presence: true
  def self.search(query)
    where("title like ? OR body like ?", "%#{query}%", "%#{query}%") 
  end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
	before_save :encrypt_password
  has_many :posts
  
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user_password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  def self.search(query)
    where("name like ? OR email like ?", "%#{query}%", "%#{query}%") 
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :set_post, only: [:show]
  def new
    
    @page_title = 'Add Post'
    @post = Post.new
  end

  def show
  end

  def index 
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
    
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    
    @post = Post.new(post_params)
  
    if @post.save
    
        flash[:notice] = 'Post Created'
    
       redirect_to admin_posts_path
    
    else
    
      render 'new'
    flash[:alert] = 'wrong '
    end
 
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    
        flash[:notice] = 'Post Updated'
    
       redirect_to admin_posts_path
    
    else
    
      render 'new'
    
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post Gone ... !!!'
    redirect_to admin_posts_path
  end
  def set_post
      @post = Post.find(params[:id])
    end
  private
    def post_params
  
      params.require(:post).permit(:title, :category_id, :user_id, :tags, :body, :image)
  
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_foot.html.erb
<footer>
  <p>Copyright &copy; 2017,BLAog.com | <a href="login.html">Admin Login</a></p>
</footer>

app/views/layouts/_nav.html.erb
<nav>
   <ul class="navul left">
    <li><%= link_to "home", pages_index_path %></li>
    <li><%= link_to "fast", pages_slow_path %></li>
    <li><%= link_to "slow", pages_fast_path %></li>
    <li><%= link_to "styles ", '' %><span class="darrow">&#9660;</span>
      <ul class="sub2">
       <% Style.all.each do |style|%>
        <li><%= link_to style.name , style_path(style) %></li>
       <% end %>
       
       <% if current_user %>
         <li class='devider'>
          ----------------
         </li>
         <li>
           <%= link_to(new_style_path) do %>
             New Style
           
          <% end%>
         </li>
        
    
        <% end%>
       
      </ul>
    </li>
    
    <li><%= link_to "ingredients ", '' %><span class="darrow">&#9660;</span>
      <ul class="sub2">
       <% Ingredient.all.each do |ingredient|%>
        <li><%= link_to ingredient.name , ingredient_path(ingredient) %></li>
       <% end %>
       <% if current_user %>
         <li class='devider'>
          ----------------
         </li>
         <li>
           <%= link_to(new_ingredient_path) do %>
             New Ingredient
           
          <% end%>
         </li>
    
        <% end%>
         
      </ul>
      
    </li>
   </ul>
   
  <ul class="navul right">
    <% if !current_user %>
    <li><%= link_to "sign up", new_user_registration_path %></li>
    <li><%= link_to "sign in", new_user_session_path %></li>
    <% else %>
    <li><%= link_to current_user.username %><span class="darrow">&#9660;</span>
      <ul class="sub1">
       
        <li><%= link_to "create recipe ", new_recipe_path %></li>
        <li><%= link_to "create article ", new_article_path %></li>
        <li><%= link_to "edit profile", edit_user_registration_path %></li>
        <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "bla sub1a", '' %><span class="larrow">&#9668;</span><!--9658 is rarrow-->
          <ul class="sub1a">
             <li><%= link_to "create recipe ", new_recipe_path %></li>
             <li><%= link_to "create article ", new_article_path %></li>
          </ul>
        </li>
      </ul>
    </li>
    
    <li><%= link_to "username ", '' %><span class="darrow">&#9660;</span>
      <ul class="sub2">
       
        <li><%= link_to "create recipe ", new_recipe_path %></li>
        <li><%= link_to "create article ", new_article_path %></li>
        <li><%= link_to "edit profile", edit_user_registration_path %></li>
        <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
        
        <li><%= link_to "recipes ", new_recipe_path %></li>
        
      </ul>
      
    </li>
    
    <li><%= link_to "username ", '' %><span class="darrow">&#9660;</span>
      <ul class="sub3">
       
        <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
        
        <li><%= link_to "recipes ", new_recipe_path %></li>
        <li><%= link_to "articles ", new_article_path %></li>
        <li><%= link_to "edit profile", edit_user_registration_path %></li>
        <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
      </ul>
      
    </li>
    <% end %>
   </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="list-group">
  <a href="" class="list-group-item">News</a>
  <a href="" class="list-group-item">Tutorials</a>
  <a href="" class="list-group-item">Releases</a>
  <a href="" class="list-group-item">Events</a>
</div>

app/views/layouts/admin/_formedit.html.erb
<%= form_for [:admin, @category] do |f| %>
  
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :name, class:"form-control" %>
  </div><br />
  <%= f.submit 'create', class:" submitbtn" %>
  <%= link_to "Cancel", admin_categories_path, class:"btn btn-default"%>
  
<% end %>

app/views/layouts/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>

  <%= form_tag(admin_posts_path, :method => "get", id: "search-form", class:"search-form pull-right") do  %>
    <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:'form-control' %>
    </div>
    <%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
  <% end %>
  
<% elsif params[:controller] == 'admin/categories' %>
  
  <%= form_tag(admin_categories_path, :method => "get", id: "search-form", class:"search-form pull-right") do  %>
    <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Categories", class:'form-control' %>
    </div>
    <%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
  <% end %>
  
<% elsif params[:controller] == 'admin/users' %>
    
    <%= form_tag(admin_users_path, :method => "get", id: "search-form", class:"search-form pull-right") do  %>
    <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Users", class:'form-control' %>
    </div>
    <%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
  <% end %>
  
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= tinymce_assets %>

</head>

<body>


bbbbbbbbbbbb backend admin

    <nav class="navbar navbar-default " role="navigation">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html"><h1>BLAog<span>/Managing</span></h1></a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>"><%= link_to "Posts", admin_posts_path %></li>
            <li class="<%= params[:controller] == 'admin/categories' ? 'active' : '' %>"><%= link_to "Categories", admin_categories_path %></li>
            <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>"><%= link_to "Users", admin_users_path %></li>
          </ul>

         <%= render 'layouts/admin/search' %>

        </div><!--/.nav-collapse -->

      </div>
    </nav>
    
    <section>
      <div class="container">
        <div class="row">

          <div class="col-md-12">
            <!-- FLASH-ALERTS-NOTICES-->
            <% if flash[:notice] %>
            <p class="notice"><%= notice %></p>
            <% end %>
            <% if flash[:alert] %>
            <p class="alert"><%= alert %></p>
            <% end %>
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-danger"><%= flash[:alert] %></div>
            <% end %>
<!-- EINDE   FLASH-ALERTS-NOTICES--> 
<%= yield %>		
		  </div>

		</div> 
      </div>
    </section>

    <footer>
      <p><small>Copyright &copy; 2017,BLAog.com | <a href="login.html">Admin Login</small></a></p>
    </footer>

  


   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
bbbbbbbbbbbb FRONt
<!-- NAV -->  
 <nav class="navbar navbar-default " role="navigation">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html"><h1>BLAog</h1></a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'posts/index' ? 'active' : '' %>"><%= link_to "home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
          
          

        </div><!--/.nav-collapse -->

      </div>
    </nav>
<!-- EINDE   NAV -->  
    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
<!-- FLASH-ALERTS-NOTICES-->
            <% if flash[:notice] %>
            <p class="notice"><%= notice %></p>
            <% end %>
            <% if flash[:alert] %>
            <p class="alert"><%= alert %></p>
            <% end %>
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-danger"><%= flash[:alert] %></div>
            <% end %>
<!-- EINDE   FLASH-ALERTS-NOTICES-->          
<%= yield %>
            
          </div>

          <div class="col-md-4">
            <%= render 'layouts/sidebar' %><!--in plaats van in de viewpatials gewoon in layouts gedaan -->
          </div>

        </div>
      </div>
    </section>

    <%= render 'layouts/foot' %><!--in plaats van in de viewpatials gewoon in layouts gedaan -->
    
  


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <script src="js/bootstrap.js"></script>
    
</body>
</html>