config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  
  get 'contact' => 'contacts#new'

  get 'contacts/create'

 get 'about' => 'about#index'
  namespace :admin do
  get 'sessions/new'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/show'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/show'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  get 'posts/index'

  get 'posts/show'
  resources :posts, :categories, :comments
  resources  "contacts", only: [:new, :create]
  
  namespace :admin do
  
    resources :posts, :categories, :comments, :users
  end

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  
  validates :name, presence: true
  def self.search(query)
    where("name like ?", "%#{query}%") 
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user  
  has_many :comments
  
  validates :title, presence: true
  validates :category_id, presence: true
  
  validates :body, presence: true
  def self.search(query)
    where("title like ? OR body like ?", "%#{query}%", "%#{query}%") 
  end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
	before_save :encrypt_password
  has_many :posts
  
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user_password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  def self.search(query)
    where("name like ? OR email like ?", "%#{query}%", "%#{query}%") 
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def destroy
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
 before_action :set_post, only: [:show]
  def new
    
    @page_title = 'Add Post'
    @post = Post.new
  end

  def show
  end

  def index 
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
    
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    
    @post = Post.new(post_params)
  
    if @post.save
    
        flash[:notice] = 'Post Created'
    
       redirect_to admin_posts_path
    
    else
    
      render 'new'
    flash[:alert] = 'wrong '
    end
 
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    
        flash[:notice] = 'Post Updated'
    
       redirect_to admin_posts_path
    
    else
    
      render 'new'
    
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post Gone ... !!!'
    redirect_to admin_posts_path
  end
  def set_post
      @post = Post.find(params[:id])
    end
  private
    def post_params
  
      params.require(:post).permit(:title, :category_id, :user_id, :tags, :body, :image)
  
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  def new
  end

  def create
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def new
    
    @page_title = 'Add User'
    @user = User.new
  end

  def show
  end

  def index
    
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @users = User.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    
    @user = User.new(user_params)
  
    if @user.save
    
        flash[:notice] = 'user Created'
    
       redirect_to admin_users_path
    
    else
    
      render 'new'
    flash[:alert] = 'wrong '
    end
 
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    
        flash[:notice] = 'user Updated'
    
       redirect_to admin_users_path
    
    else
    
      render 'new'
    flash[:alert] = 'wrong '
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'user Gone ... !!!'
    redirect_to admin_users_path
  end
  private
    def user_params
  
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :set_post, only: [:show]
  def new
    
    @page_title = 'Add Post'
    @post = Post.new
  end

  def show
  end

  def index 
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
    
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    
    @post = Post.new(post_params)
  
    if @post.save
    
        flash[:notice] = 'Post Created'
    
       redirect_to admin_posts_path
    
    else
    
      render 'new'
    flash[:alert] = 'wrong '
    end
 
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    
        flash[:notice] = 'Post Updated'
    
       redirect_to admin_posts_path
    
    else
    
      render 'new'
    
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post Gone ... !!!'
    redirect_to admin_posts_path
  end
  def set_post
      @post = Post.find(params[:id])
    end
  private
    def post_params
  
      params.require(:post).permit(:title, :category_id, :user_id, :tags, :body, :image)
  
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/posts/create.html.erb
<h1>Admin::Posts#create</h1>
<p>Find me in app/views/admin/posts/create.html.erb</p>

app/views/admin/posts/destroy.html.erb
<h1>Admin::Posts#destroy</h1>
<p>Find me in app/views/admin/posts/destroy.html.erb</p>

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>
<p>Find me in app/views/admin/posts/edit.html.erb</p>
<h1>add new post</h1>
<!--<script>
  $(function() {
    $('textarea#froala-editor').froalaEditor()
  });
</script>-->
<h2>Edit New Post</h2>
<div class="well">
  
<%= tinymce %>
<%= form_for [:admin, @post] do |f| %>
<!-- Check for errors -->
	
	<% if @post.errors.any? %>
	
		<% @post.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger">
				<%= msg %>

			</div>

		<% end %>

	 <% end %>

	 <div class="form-group">
	 	<%= f.label :title %><br />
	 	<%= f.text_field :title, class:'form-control' %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :category %><br />
	 	<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :author %><br />
	 	<%= f.select :user_id, User.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :image %><br />
	 	<%= f.file_field :image %>
	 </div>

		

	  <div class="form-group">
	 	<%= f.label :tags %><br />
	 	<%= f.text_area :tags, class:'form-control' %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :body %><br />
	 	<%= f.text_area :body, :class => "tinymce", id:'froala-editor' %>
	 </div>

	 <hr />

	 <%= f.submit "Edit", class:'submitbtn' %>
	 <%= link_to "Cancel", admin_categories_path, class:'btn btn-default' %>

<% end %>
</div>

app/views/admin/posts/index.html.erb
<h1>Admin::Posts#index</h1>
<p>Find me in app/views/admin/posts/index.html.erb</p>
<%= will_paginate @posts %>
<div class="class">
	<h2>Hai Welkom</h2>
	
</div>
<div class="well">
				
	<h2 class="page-header">Posts<%= link_to "Create New", new_admin_post_path, class:'btn btn-success pull-right' %> </h2>
	<% if @posts.exists? %>
		<table class="table">

			<tr>
				<th>Post Title</th>
				<th>Post Category</th>
				<th>Post Body</th>
				<th>Post Created</th>
				<th>Actions</th>
			</tr>

			<% @posts.each do |post| %>

				<tr>
					<td><%= link_to post.title, post %></td>
					<td><%= post.category.name %></td>
					<td><%= post.body.html_safe %></td>
					<td><%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
					<td><%= link_to "Edit", edit_admin_post_path(post), class:'btn btn-primary' %>
						<%= link_to "Delete", admin_post_path(post), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you SURE'} %>
					</td>
				</tr>

			<% end %>
		
		</table>
		<%= will_paginate @posts %>
	<% else %>
		<p>There Are No Posts </p>
	<% end %>

</div>

app/views/admin/posts/new.html.erb
<!--<script>
	$(function() {
    $('textarea#froala-editor').froalaEditor()
  });

</script>-->
<h1>Admin::Posts#new</h1>
<p>Find me in app/views/admin/posts/new.html.erb</p>
<h1>add new post</h1>

<h2>Add New Post</h2>
<div class="well">
  
<%= tinymce %>

<%= form_for [:admin, @post] do |f| %>
<!-- Check for errors -->
	
	<% if @post.errors.any? %>
	
		<% @post.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger">
				<%= msg %>

			</div>

		<% end %>

	 <% end %>

	 <div class="form-group">
	 	<%= f.label :title %><br />
	 	<%= f.text_field :title, class:'form-control' %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :category %><br />
	 	<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :author %><br />
	 	<%= f.select :user_id, User.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :image %><br />
	 	<%= f.file_field :image %>
	 </div>

		

	  <div class="form-group">
	 	<%= f.label :tags %><br />
	 	<%= f.text_area :tags, class:'form-control' %>
	 </div>
	 <div class="form-group" id:"edit">
	 	<%= f.label :body %><br />
	 	<%= f.text_area :body, :class => "tinymce", :rows => 11, :cols => 120, id:'froala-editor' %>
	 </div>

	 <hr />

	 <%= f.submit "Very New", class:'submitbtn' %>
	 <%= link_to "Cancel", admin_categories_path, class:'btn btn-default' %>

<% end %>
</div>

app/views/admin/posts/show.html.erb
<h1>Admin::Posts#show</h1>
<p>Find me in app/views/admin/posts/show.html.erb</p>
<p>
  <strong><%= @post.body %></strong>
  
</p>


<p style="background:#f4ebeb; padding:15px;">
  
  <%= @post.category.name %>
</p>

app/views/admin/posts/update.html.erb
<h1>Admin::Posts#update</h1>
<p>Find me in app/views/admin/posts/update.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/posts/index.html.erb
<div class="row">
              <div class="col-md-6">
                <div class="post">
                  <img src="img/plaatje2.png" alt="">
                  <div class="post-content">

                    <h3>Handmatig Ruby On Rails installeren. </h3> 
                      <p>
                        <small>Posted by me on sje3ben 1-1800</small>
                        om te beginnen. rubyinstaller.org
                        installeer  ruby dan  cd DevKit
                        ruby dk.rb init  dit maakt config.yml file
                        type config.yml  dit zoekt je rubyversion
                        ruby dk.rb install  ditinst ruby in devkit
                        gem install json --platform=ruby  dit inst json
                        ruby -rubygems -e "require 'json'; puts JSON.load('[42]').inspect"  dit test of json is ginst. als 42 dan goed
                      </p>
                      <a href="" class="btn btn-primary btn-block">Read More</a>

                  </div>
                </div>
              </div>
            
            
              <div class="col-md-6">
                <div class="post">
                  <img src="img/plaatje2.png" alt="">
                  <div class="post-content">
                    <h3>Handmatig Ruby On Rails installeren. </h3> 
                      <p>
                        <small>Posted by you on sje3ben 2-1800</small>
                        om te beginnen. rubyinstaller.org
                        installeer  ruby dan  cd DevKit
                        ruby dk.rb init  dit maakt config.yml file
                        type config.yml  dit zoekt je rubyversion
                        ruby dk.rb install  ditinst ruby in devkit
                        gem install json --platform=ruby  dit inst json
                        ruby -rubygems -e "require 'json'; puts JSON.load('[42]').inspect"  dit test of json is ginst. als 42 dan goed
                      </p>
                      <a href="" class="btn btn-primary btn-block">Read More</a>   
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="post">
                  <img src="img/plaatje2.png" alt="">
                  <div class="post-content">

                    <h3>Handmatig Ruby On Rails installeren. </h3> 
                      <p>
                        <small>Posted by me on sje3ben 1-1800</small>
                        om te beginnen. rubyinstaller.org
                        installeer  ruby dan  cd DevKit
                        ruby dk.rb init  dit maakt config.yml file
                        type config.yml  dit zoekt je rubyversion
                        ruby dk.rb install  ditinst ruby in devkit
                        gem install json --platform=ruby  dit inst json
                        ruby -rubygems -e "require 'json'; puts JSON.load('[42]').inspect"  dit test of json is ginst. als 42 dan goed
                      </p>
                      <a href="" class="btn btn-primary btn-block">Read More</a>

                  </div>
                </div>
              </div>
            
            
              <div class="col-md-6">
                <div class="post">
                  <img src="img/plaatje2.png" alt="">
                  <div class="post-content">
                    <h3>Handmatig Ruby On Rails installeren. </h3> 
                      <p>
                        <small>Posted by you on sje3ben 2-1800</small>
                        om te beginnen. rubyinstaller.org
                        installeer  ruby dan  cd DevKit
                        ruby dk.rb init  dit maakt config.yml file
                        type config.yml  dit zoekt je rubyversion
                        ruby dk.rb install  ditinst ruby in devkit
                        gem install json --platform=ruby  dit inst json
                        ruby -rubygems -e "require 'json'; puts JSON.load('[42]').inspect"  dit test of json is ginst. als 42 dan goed
                      </p>
                      <a href="" class="btn btn-primary btn-block">Read More</a>   
                  </div>
                </div>
              </div>
            </div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>
<p>
  <strong><%= @post.body %></strong>
  
</p>


<p style="background:#f4ebeb; padding:15px;">
  
  <%= @post.category.name %>
</p>